language: node_js

matrix:
  include:
    # lint
    - node_js: 8 # MAINTENANCE until December 2019
      env: TEST_SUITE=lint
    - node_js: 10
      env: TEST_SUITE=lint

    # coverage
    - node_js: 10
      env: TEST_SUITE=coveralls

    # test suite on headless Chrome browser
    - node_js: 10
      env:
        - TEST_SUITE=test:browser
          TEST_BROWSER_CHROME_HEADLESS=1
      script:
        # NOTE: As commented in karma.conf.js,
        # manual installation of puppeteer@1
        # is required in order to avoid breaking
        # Travis CI on DEPRECATED Node.js 0.12 & 4.
        - npm i --save-dev puppeteer@1 && npm run $TEST_SUITE
    - node_js: 12
      env:
        - TEST_SUITE=test:browser
          TEST_BROWSER_CHROME_HEADLESS=1
      script:
        # NOTE (repeated): As commented in karma.conf.js,
        # manual installation of puppeteer@1
        # is required in order to avoid breaking
        # Travis CI on DEPRECATED Node.js 0.12 & 4.
        - npm i --save-dev puppeteer@1 && npm run $TEST_SUITE

    # test suite on Node.js only
    - node_js: 0.12 # DEPRECATED
      env: TEST_SUITE=test:node
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=test:node
    - node_js: 6 # DEPRECATED
      env: TEST_SUITE=test:node
    - node_js: 8
      env: TEST_SUITE=test:node
    - node_js: 10
      env: TEST_SUITE=test:node
    - node_js: 12
      env: TEST_SUITE=test:node
    # TBD SKIP TESTING on Windows & macOS ("osx") for now,
    # due to some known test failures
    # ...
    # - node_js: 10
    #   env: TEST_SUITE=test:node
    #   os: windows
    # - node_js: 10
    #   env: TEST_SUITE=test:node
    #   os: osx
    # ...

    # dist - full test, with help from headless Chrome browser
    - node_js: 10
      env:
        - TEST_SUITE=dist
          TEST_BROWSER_CHROME_HEADLESS=1
      script:
        # NOTE: As commented in karma.conf.js,
        # manual installation of puppeteer@1
        # is required in order to avoid breaking
        # Travis CI on DEPRECATED Node.js 0.12 & 4.
        - npm i --save-dev puppeteer@1 && npm run $TEST_SUITE

    # xxxxx
    - node_js: 10
      env: TEST_SUITE=distcheck:test:node
      script:
        - npm run compile && npm run distcheck:prepare && npm run $TEST_SUITE
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=distcheck:test:node
      script:
        - npm run compile && npm run distcheck:prepare && npm run $TEST_SUITE
    - node_js: 0.12 # DEPRECATED
      env: TEST_SUITE=distcheck:test:node
      script:
        - npm run compile && npm run distcheck:prepare && npm run $TEST_SUITE

install:
  - npm install

script:
  - npm run $TEST_SUITE
