language: node_js

matrix:
  include:
    # lint
    - node_js: 8 # EOL December 2019
      env: TEST_SUITE=lint
    - node_js: 10
      env: TEST_SUITE=lint

    # coverage
    - node_js: 10
      env: TEST_SUITE=coveralls

    # test suite on headless Chrome browser only
    - node_js: 10
      env: TEST_SUITE=test:browser
    - node_js: 10
      env: TEST_SUITE=test:browser
      os: windows
    - node_js: 10
      env: TEST_SUITE=test:browser
      os: osx # macOS

    # test suite on Node.js only
    - node_js: 10
      env: TEST_SUITE=test:node

    # test suite on Node.js & headless Chrome browser
    - node_js: 0.12 # DEPRECATED
      env: TEST_SUITE=test
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=test
    - node_js: 6 # DEPRECATED
      env: TEST_SUITE=test
    - node_js: 8 # EOL December 2019
      env: TEST_SUITE=test
    - node_js: 10
      env: TEST_SUITE=test
    - node_js: 12
      env: TEST_SUITE=test

    # test:node:skipasync on Node.js on Windows & macOS ("osx")
    # TBD SKIP TESTING on Windows & macOS ("osx") for now,
    # due to timing issues with async tests
    - node_js: 0.12 # DEPRECATED
      env: TEST_SUITE=test:node:skipasync
      os: windows
    - node_js: 0.12 # DEPRECATED
      env: TEST_SUITE=test:node:skipasync
      os: osx # macOS
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=test:node:skipasync
      os: windows
    - node_js: 10
      env: TEST_SUITE=test:node:skipasync
      os: windows
    - node_js: 10
      env: TEST_SUITE=test:node:skipasync
      os: osx # macOS
    - node_js: 12
      env: TEST_SUITE=test:node:skipasync
      os: windows

    # distcheck:test:browser
    - node_js: 10
      env: TEST_SUITE=distcheck:test:browser
      script:
        - npm run compile && npm run distcheck:prepare && npm run $TEST_SUITE

    # distcheck:test:node
    - node_js: 10
      env: TEST_SUITE=distcheck:test:node
      script:
        - npm run compile && npm run distcheck:prepare && npm run $TEST_SUITE

    # dist - full test, with help from headless Chrome browser
    - node_js: 0.12 # DEPRECATED
      env: TEST_SUITE=dist
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=dist
    - node_js: 10
      env: TEST_SUITE=dist
    - node_js: 12
      env: TEST_SUITE=dist

install:
  - npm install

script:
  - npm run $TEST_SUITE
