language: node_js

matrix:
  include:
    # lint
    - node_js: 8 # EOL December 2019
      env: TEST_SUITE=lint
    - node_js: 10
      env: TEST_SUITE=lint

    # coverage
    - node_js: 10
      env: TEST_SUITE=coveralls

    # test suite on headless Chrome browser only
    - node_js: 10
      env: TEST_SUITE=test:browser

    # test suite on Node.js only
    - node_js: 10
      env: TEST_SUITE=test:node

    # test suite on Node.js & headless Chrome browser
    - node_js: 0.12 # DEPRECATED
      env: TEST_SUITE=test
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=test
    - node_js: 6 # DEPRECATED
      env: TEST_SUITE=test
    - node_js: 8 # EOL December 2019
      env: TEST_SUITE=test
    - node_js: 10
      env: TEST_SUITE=test
    - node_js: 12
      env: TEST_SUITE=test

    # TBD SKIP TESTING on Windows & macOS ("osx") for now,
    # due to some known test failures
    # ...
    # - node_js: 10
    #   env: TEST_SUITE=test:node
    #   os: windows
    # - node_js: 10
    #   env: TEST_SUITE=test:node
    #   os: osx
    # ...

    # distcheck:test:node
    # XXX TODO:
    # - node_js: 0.12 # DEPRECATED
    #   ...
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=distcheck:test:node
      script:
        - npm run compile && npm run distcheck:prepare && npm run $TEST_SUITE
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=test:node
    # XXX TODO:
    # - node_js: 6 # DEPRECATED
    #   ...
    #   ...

    # dist - full test, with help from headless Chrome browser
    # XXX TODO:
    # - node_js: 0.12 # DEPRECATED
    #   ...
    #   ...
    - node_js: 10
      env: TEST_SUITE=test:node
    # XXX TODO:
    # - node_js: 12
    #   ...

install:
  - npm install

script:
  - npm run $TEST_SUITE
