language: node_js

matrix:
  include:
    - node_js: 10
      env: TEST_SUITE=lint
    - node_js: 10
      env: TEST_SUITE=coveralls
    - node_js: 8
      env: TEST_SUITE=test:node
      os: windows
    - node_js: 10
      env: TEST_SUITE=test:node
      os: windows
    - node_js: 10
      env: TEST_SUITE=test:node
      os: osx
    - node_js: 0.12 # DEPRECATED
      env: TEST_SUITE=test:node
    - node_js: 4 # DEPRECATED
      env: TEST_SUITE=test:node
    - node_js: 6 # DEPRECATED
      env: TEST_SUITE=test:node
    - node_js: 8
      env: TEST_SUITE=test:node
    - node_js: 12
      env: TEST_SUITE=test:node

install:
  - npm install

script: "npm run $TEST_SUITE"
